export const ASSETS = {
  icons: {
    logo: "/assets/icons/logo.svg",
    menu: "/assets/icons/menu.svg",
    close: "/assets/icons/close.svg",
  },
  backgrounds: {
    hero: "/assets/backgrounds/hero.png",
  },
  tech: {
    javascript: "/assets/tech/javascript.png",
    typescript: "/assets/tech/typescript.png",
    python: "/assets/tech/python.png",
    csharp: "/assets/tech/csharp.png",
    cplusplus: "/assets/tech/cplusplus.png",
    react: "/assets/tech/react.png",
    nextjs: "/assets/tech/nextjs.png",
    tailwind: "/assets/tech/tailwind.png",
    redux: "/assets/tech/redux.png",
    framermotion: "/assets/tech/framermotion.png",
    nodejs: "/assets/tech/nodejs.png",
    nestjs: "/assets/tech/nestjs.png",
    express: "/assets/tech/express.png",
    fastapi: "/assets/tech/fastapi.png",
    postgresql: "/assets/tech/postgresql.png",
    mongodb: "/assets/tech/mongodb.png",
    redis: "/assets/tech/redis.png",
    docker: "/assets/tech/docker.png",
    aws: "/assets/tech/aws.png",
    git: "/assets/tech/git.png",
    graphql: "/assets/tech/graphql.png",
    prisma: "/assets/tech/prisma.png",
  },
  projects: {
    backend: "/assets/projects/backend.png",
    web: "/assets/projects/web.png",
    mobile: "/assets/projects/mobile.png",
    creator: "/assets/projects/creator.png",
    bikebuddies: "/assets/projects/screenshots/bikebuddies.jpg",
    boxFactory: "/assets/projects/screenshots/box-factory.jpg",
    aakaar: "/assets/projects/screenshots/aakaar.jpg",
    hrms: "/assets/projects/screenshots/hrms.jpg",
    xcubit: "/assets/projects/screenshots/xcubit.jpg",
    vastav: "/assets/projects/screenshots/vastav.jpg",
  },
  models: {
    planet: "/models/planet/scene.gltf",
  },
} as const;
